# 环境和机器人设置
setup:
  font_path: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc" # !请根据你的系统修改!
  left_robot_ip: "192.168.188.200"
  right_robot_ip: "192.168.188.201"
  camera_serials:
    left_hand: "CP1Z84200072"
    right_hand: "CP1Z8420005H"
    head: "CP1Z842000WD"
    chest: "CL8NB4300WN"
  # --- 其他视觉相关配置 (示例) ---
  yolo_models:
    default: '/home/sage/Frank/code/dualarm_robot_project_1/software/config/best_bottle.pt',
    bottle: '/home/sage/Frank/code/dualarm_robot_project_1/software/config/best_bottle.pt',
    # 可以添加更多模型...
  calibration_files:
    left: "./calibration_yaml/config_left.yaml"  # 左臂手眼标定文件
    right: "./calibration_yaml/config_left.yaml" # 右臂手眼标定文件
  # 可选：为每个机器人指定夹爪的 Modbus ID (如果不是默认的 9)
  # left_gripper_id: 9
  # right_gripper_id: 9
  window_width: 750
  window_height: 380 # 略微增加高度以容纳夹爪状态
  font_size: 18

# 手柄控制配置文件
controls:
  # --- Movement Controls ---
  left_arm_x_pos: { type: hat, index: 0, axis: y, direction: -1 }
  left_arm_x_neg: { type: hat, index: 0, axis: y, direction: 1 }
  left_arm_y_pos: { type: hat, index: 0, axis: x, direction: 1 }
  left_arm_y_neg: { type: hat, index: 0, axis: x, direction: -1 }
  left_arm_z_pos: { type: button, index: 4 } # LB
  left_arm_z_neg: { type: axis, index: 2, threshold: 0.1, direction: 1 } # LT

  # 右臂控制
  right_arm_x_pos: { type: button, index: 3 } # Y
  right_arm_x_neg: { type: button, index: 0 } # A
  right_arm_y_pos: { type: button, index: 2 } # X
  right_arm_y_neg: { type: button, index: 1 } # B
  right_arm_z_pos: { type: button, index: 5 } # RB
  right_arm_z_neg: { type: axis, index: 5, threshold: 0.1, direction: 1 } # RT

  # --- Gripper Toggle Controls ---
  gripper_toggle_left: { type: button, index: 9 }  # R3 (右摇杆按下)
  gripper_toggle_right: { type: button, index: 10 } # Guide (Xbox Logo 按钮 - 可能无效!)

  # --- Speed Adjustment Controls ---
  speed_increase: { type: button, index: 6 } # Start 按钮
  speed_decrease: { type: button, index: 11 } # Back 按钮

# 速度和通用设置
settings:
  initial_xy_speed: 40.0
  initial_z_speed: 30.0
  speed_increment: 5.0
  min_speed: 5.0
  max_speed: 100.0
  acc: 100
  arot: 10
  t: 0.1
  trigger_threshold: 0.1
  # 可选：夹爪操作参数
  # gripper_speed: 150
  # gripper_force: 100

# 退出程序的按钮 (现在由 Start 控制速度，所以移除或映射到其他键)
quit_button: { type: button, index: 7 } # 可以移除，使用 Esc 或关闭窗口